version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - demoapp-network

  application:
    container_name: demo-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mysql
    networks:
      - demoapp-network

networks:
  demoapp-network:
    driver: bridge

volumes:
  mysql-data: